pull_request_title: 'i18n: update crowdin translation'
commit_message: 'i18n: update translations for `%language%`'
files:
  - source: /src/main/resources/assets/meteor-translate/lang/en_us.json
    translation: /src/main/resources/assets/meteor-translate/lang/%locale_with_underscore%.json
